--- #YAML:1.0
name:               Business-OnlinePayment-Litle
version:            0.5
abstract:           Litle & Co. Backend for Business::OnlinePayment
author:
    - Jason Hall <jayce@lug-nut.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Business::CreditCard:  0
    Business::OnlinePayment:  0
    Business::OnlinePayment::HTTPS:  0
    Net::SSLeay:          0
    Test::More:           0
    Tie::IxHash:          0
    XML::Simple:          0
    XML::Writer:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
